name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # as suggested in README:
    - name: Install Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y build-essential pkg-config libicu-dev libssl-dev libldap2-dev libpam0g-dev postgresql-client-18 --no-install-recommends
        curl "https://static.rust-lang.org/rustup/archive/1.29.0/x86_64-unknown-linux-gnu/rustup-init" > rustup-init
        chmod +x rustup-init
        sudo ./rustup-init -y --profile minimal --default-toolchain 1.97.1 --default-host x86_64-unknown-linux-gnu
        source $HOME/.cargo/env
        cargo --version && rustc --version
    - name: Build
      run: |
        export PGRUST_PGSHAREDIR="$(pwd)/vendor/postgres-18.3/share"
        cargo build --release --locked --bin postgres
    - name: Run Unittest
      run: |
        export PGRUST_PGSHAREDIR="$(pwd)/vendor/postgres-18.3/share"
        cargo test --locked --release --all || true
    - name: Run Regression
      run: |
        export PGRUST_PGSHAREDIR="$(pwd)/vendor/postgres-18.3/share"
        export PGRUST_BIN="$(pwd)/target/release/postgres"
        ./scripts/run-regression
    # Releasing pgrust binary in this way will cost me dearly,
    # so I'm not doing this (sry).
    # - name: Upload Binary
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: pgrust-binary
    #     path: target/release/postgres
